# Generated by Django 5.0 on 2023-12-28 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('crm', models.CharField(max_length=5, unique=True)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='profissional_saude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.profissional'),
        ),
        migrations.DeleteModel(
            name='ProfissionalSaude',
        ),
    ]
